### ISSUE TITLE
Chunks do not correctly generate in the demos.

### ISSUE THREAD

**Issue by Morphexe** [BLaZeKiLL/VloxyEngine#87] opened 2023-02-03 12:39 UTC
Just tried running the demos on my machine, both IL2CPP and Mono versions have the same weird behaviour.
Some chunks generate in the wrong positions, and there are empty holes everything on the map that gets generated.

Check the examples below:

I haven`t dug into the code yet, but this happens every time I run the demo ( different holes and errors) - generation settings are the default ones.

![image](https://user-images.githubusercontent.com/17990387/216605531-9b38e732-3174-43de-8b11-0ba3198b668c.png)
![image](https://user-images.githubusercontent.com/17990387/216605724-feb39ec8-e573-4eb5-9971-dc279a706714.png)

**Comment by BLaZeKiLL** [comment] 2023-02-03 19:16
Yeah this a known issue, probably something to do with chunk region update, haven’t able too figure out the real root cause.

**Comment by AldeRoberge** [comment] 2023-03-02 22:55
I am observing the same behavior on the latest version, in editor : 

![image](https://user-images.githubusercontent.com/4276275/222578572-45e1021b-025c-4e62-98c6-5e7137145007.png)

```
ArgumentException: An item with the same key has already been added. Key: int3(-96, -160, -224)
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <75633565436c42f0a6426b33f0132ade>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <75633565436c42f0a6426b33f0132ade>:0)
CodeBlaze.Vloxy.Engine.Components.ChunkBehaviourPool.Claim (Unity.Mathematics.int3 position) (at Packages/io.codeblaze.vloxyengine/Runtime/Engine/Components/ChunkBehaviourPool.cs:56)
CodeBlaze.Vloxy.Engine.Jobs.Mesh.MeshBuildScheduler.Complete () (at Packages/io.codeblaze.vloxyengine/Runtime/Engine/Jobs/Mesh/MeshBuildScheduler.cs:230)
CodeBlaze.Vloxy.Engine.Jobs.Mesh.MeshBuildScheduler.LateUpdate () (at Packages/io.codeblaze.vloxyengine/Runtime/Engine/Jobs/Mesh/MeshBuildScheduler.cs:98)
CodeBlaze.Vloxy.Engine.Jobs.VloxyScheduler.LateUpdate () (at Packages/io.codeblaze.vloxyengine/Runtime/Engine/Jobs/VloxyScheduler.cs:59)
CodeBlaze.Vloxy.Engine.World.VloxyWorld.LateUpdate () (at Packages/io.codeblaze.vloxyengine/Runtime/Engine/World/VloxyWorld.cs:100)

```

**Comment by BLaZeKiLL** [comment] 2023-03-02 23:39
Yeah I am planning to re-write the schedulers and the logic that decides which chunks to build, also introducing some throttling in chunk updates could help I believe.

Currently the height map (chunk data) generation is also implemented as a job which limits extensibility as you are restricted to burst compatible c#. Maybe data generation can have it's own plain old dotnet thread it maybe slower but data generation isn't going to be that expensive anyway relative to mesh generation although that depends on how complex the user want the generation to be. Still to facilitate extensibility this seems like a better approach we can always make parts of it jobs based (the actual data filling part)

**Comment by AldeRoberge** [comment] 2023-03-04 02:50
Hello @BLaZeKiLL ,

I have found this other project with a similar goal. It is not for URP, but the load is fast.

https://github.com/bbtarzan12/Unity-Procedural-Voxel-Terrain

You might want to take a look!

**Comment by BLaZeKiLL** [comment] 2023-03-04 04:29
> Hello @BLaZeKiLL ,
> 
> I have found this other project with a similar goal. It is not for URP, but the load is fast.
> 
> https://github.com/bbtarzan12/Unity-Procedural-Voxel-Terrain
> 
> You might want to take a look!

I'll take look, if you have done some benchmarks with the same amount of chunk counts for both, how much faster do you think it is ?

**Comment by BLaZeKiLL** [comment] 2023-03-04 04:49
One difference I see that does impact performance with respect to the implementation mentioned above is using simple arrays to store voxels, while in Vloxy engine we use a compressed data (Run-length encoding/Interval Trees) structure which does lead to O(logn) read time compared to O(1) of naive arrays.

**Comment by AldeRoberge** [comment] 2023-03-04 15:40
I was able to produce the bug mentioned above every time by moving fast (holding shift)

When moving too fast, the error occurs and the chunks never unload.

**Comment by BLaZeKiLL** [comment] 2023-03-24 06:37
New scheduler is merged into the develop branch which should fix this issue, please try it out @

**Closed** 2023-04-22 07:50 UTC
Labels: bug

**Comment by AldeRoberge** [comment] 2023-04-27 01:38
I have tested, and I can confirm it works!
